### ISSUE TITLE
web-doc: update hooks for creating custom fields 

### ISSUE THREAD

**Issue by raftaar1191** [impress-org/give-docs#164] opened 2018-05-03 06:41 UTC
User Story
As a developer who wants to add custom fields in Donation forms s/he is not able to see the donation details that he has updated in the Donation Details page

The existing doc contains outdated hooks need to update that 

Doc Link: https://givewp.com/documentation/developers/how-to-create-custom-form-fields/

![image](https://user-images.githubusercontent.com/22215595/39562768-1725d3f0-4ecb-11e8-9e70-8c3cd8f2f3bf.png)

**Comment by mathetos** [comment] 2019-01-17 03:14
Duplicate of #166

**Closed by mathetos** 2019-01-17 03:14 UTC
